name: Sample

on:
  push:
    branches:
      - main

jobs:
  sample-demo:
    runs-on: ubuntu-latest
    container: python:3.10.4-slim-buster
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run sample demo
        run: python3 src/multipy_cli/sample.py
